---
ticker:
  tools: '/home/pi/rpi-rgb-led-matrix'
  settings:
    brightness: 50

spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:data/mydb
    username: SA
    password: lEtmEIn
    initializationMode: always
  flyway:
    enabled: true
