CREATE TABLE GIF(
    ID BIGINT NOT NULL PRIMARY KEY,
    DATA BLOB(1G),
    NAME VARCHAR(255),
    PATH VARCHAR(255)
);
CREATE SEQUENCE GIF_SEQ AS INTEGER START WITH 1 INCREMENT BY 50


CREATE TABLE PLAYLIST(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    SHUFFLE BOOLEAN NOT NULL,
    WAIT_TIME DOUBLE NOT NULL
);

CREATE SEQUENCE PLAYLIST_SEQ AS INTEGER START WITH 1 INCREMENT BY 50

CREATE TABLE PLAYLIST_ENTRIES(
    PLAYLISTS_ID BIGINT NOT NULL,
    ENTRIES_ID BIGINT NOT NULL,
    CONSTRAINT FK44M5X6SRYTVNFC4FS2VAVW5GM FOREIGN KEY(ENTRIES_ID) REFERENCES GIF(ID),
    CONSTRAINT FKJ8QDEIDKYF4US1A0J3LEUIM4W FOREIGN KEY(PLAYLISTS_ID) REFERENCES PLAYLIST(ID)
);

CREATE TABLE PREFERENCES_ENTITY(
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    VALUE VARCHAR(255)
);
CREATE TABLE SCROLLING_TEXT(
    ID BIGINT NOT NULL PRIMARY KEY,
    BACKGROUND VARBINARY(255),
    FONT VARCHAR(255),
    OUTLINE_COLOR VARBINARY(255),
    SPACING INTEGER,
    SPEED INTEGER,
    STARTX INTEGER,
    STARTY INTEGER,
    TEXT VARCHAR(255),
    TEXT_COLOR VARBINARY(255)
);
CREATE SEQUENCE SCROLLING_TEXT_SEQ AS INTEGER START WITH 1 INCREMENT BY 50
