CREATE TABLE GIF(
    ID UUID NOT NULL PRIMARY KEY,
    DATA BLOB(1G),
    NAME VARCHAR(255),
    PATH VARCHAR(255)
);

CREATE TABLE PLAYLIST(
    ID UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    SHUFFLE BOOLEAN NOT NULL,
    WAIT_TIME DOUBLE NOT NULL
);

CREATE TABLE PLAYLIST_ENTRIES(
    PLAYLISTS_ID UUID NOT NULL,
    ENTRIES_ID UUID NOT NULL,
    CONSTRAINT FK44M5X6SRYTVNFC4FS2VAVW5GM FOREIGN KEY(ENTRIES_ID) REFERENCES GIF(ID),
    CONSTRAINT FKJ8QDEIDKYF4US1A0J3LEUIM4W FOREIGN KEY(PLAYLISTS_ID) REFERENCES PLAYLIST(ID)
);

CREATE TABLE PREFERENCES_ENTITY(
    KEY VARCHAR(255) NOT NULL PRIMARY KEY,
    VALUE VARCHAR(255)
);
CREATE TABLE SCROLLING_TEXT(
    ID UUID NOT NULL PRIMARY KEY,
    BACKGROUND VARBINARY(255),
    FONT VARCHAR(255),
    OUTLINE_COLOR VARBINARY(255),
    SPACING INTEGER,
    SPEED INTEGER,
    STARTX INTEGER,
    STARTY INTEGER,
    TEXT VARCHAR(255),
    TEXT_COLOR VARBINARY(255)
);
